server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hibernate.default_schema: public
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.office365.com
    port: 587
    username: ngtbang2264.dev@gmail.com
    password: ${MAIL_PASSWO RD_SERVER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
